import { Link } from '@tanstack/react-router';
import { ArrowRight, Check, Phone } from 'lucide-react';
import { useEffect, useRef, useState, type ReactNode } from 'react';
import { brands, common, type Highlight } from '@/content/site';
import { useLanguage } from '@/context/language';
import { media } from '@/assets/media';
import { cn } from '@/lib/utils';

export function BrandArc({className}:{className?:string}){return <svg aria-hidden="true" viewBox="0 0 260 180" className={cn('pointer-events-none text-primary',className)} fill="none"><path d="M8 162C58 161 113 142 152 104C182 75 200 41 217 12" stroke="currentColor" strokeWidth="10" strokeLinecap="round"/><path d="M188 21L219 8L226 41" stroke="currentColor" strokeWidth="10" strokeLinecap="round" strokeLinejoin="round"/></svg>}
export function HighlightTitle({text,as='h2',className}:{text:Highlight;as?:'h1'|'h2'|'h3';className?:string}){const C=as;return <C className={cn('break-words font-extrabold leading-[1.08] text-brand',className)}>{text.before}<span className="text-primary">{text.highlight}</span>{text.after}</C>}
export function Eyebrow({children,light=false}:{children:ReactNode;light?:boolean}){return <p className={cn('flex items-center gap-3 text-[0.68rem] font-extrabold uppercase tracking-label',light?'text-brand-foreground/75':'text-brand')}><span className="h-0.5 w-6 bg-primary"/>{children}</p>}
export function Reveal({children,className,delay=0}:{children:ReactNode;className?:string;delay?:number}){const ref=useRef<HTMLDivElement>(null);const[seen,setSeen]=useState(false);useEffect(()=>{const el=ref.current;if(!el)return;const o=new IntersectionObserver(([e])=>{if(e?.isIntersecting){setSeen(true);o.disconnect()}},{threshold:.12});o.observe(el);return()=>o.disconnect()},[]);return <div ref={ref} style={{transitionDelay:`${delay}ms`}} className={cn('reveal',seen&&'reveal-visible',className)}>{children}</div>}
export function ButtonLink({to,children,variant='primary',className}:{to:'/'|'/about'|'/expertise'|'/services'|'/methodology'|'/references'|'/contact';children:ReactNode;variant?:'primary'|'outline'|'light';className?:string}){return <Link to={to} className={cn('inline-flex min-h-12 items-center justify-center gap-2 rounded-sm px-6 py-3 text-sm font-extrabold transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring',variant==='primary'&&'bg-primary text-primary-foreground shadow-button hover:-translate-y-0.5 hover:bg-primary-hover',variant==='outline'&&'border border-brand text-brand hover:bg-brand hover:text-brand-foreground',variant==='light'&&'bg-surface text-brand hover:bg-surface-muted',className)}>{children}<ArrowRight className="h-4 w-4"/></Link>}
export function PageHero({eyebrow,title,lead,image,alt}:{eyebrow:string;title:Highlight;lead:string;image:string;alt:string}){const{language}=useLanguage();return <section className="relative flex min-h-[34rem] items-end overflow-hidden bg-brand sm:min-h-[36rem] lg:min-h-[60svh]"><img src={image} alt={alt} className="absolute inset-0 h-full w-full object-cover" width="1920" height="1440" fetchPriority="high"/><div className="absolute inset-0 bg-[linear-gradient(90deg,var(--brand)_0%,color-mix(in_oklab,var(--brand)_91%,transparent)_55%,color-mix(in_oklab,var(--brand)_42%,transparent)_100%)]"/><BrandArc className="absolute -bottom-12 right-0 w-56 opacity-35 sm:w-72 lg:right-16 lg:w-[28rem]"/><div className="container-shell relative py-10 sm:py-14 lg:py-20"><div className="mb-6 grid grid-cols-[auto_auto_minmax(0,1fr)] items-center gap-2 text-xs font-semibold text-brand-foreground/70 sm:mb-8"><Link to="/" className="shrink-0">{common.home[language]}</Link><span>/</span><span className="min-w-0 truncate">{eyebrow}</span></div><Eyebrow light>{eyebrow}</Eyebrow><HighlightTitle as="h1" text={title} className="mt-5 max-w-4xl text-4xl text-brand-foreground sm:text-5xl lg:text-7xl"/><p className="mt-5 max-w-2xl text-base leading-7 text-brand-foreground/80 sm:mt-6 sm:text-lg">{lead}</p></div></section>}
const logoModules=import.meta.glob('/src/assets/clients/*.{svg,png,webp}',{eager:true,query:'?url',import:'default'}) as Record<string,string>;
const logoNames=['nike','mango','tommy-hilfiger','calvin-klein','crocs','hm'];
export function ClientLogos({marquee=false}:{marquee?:boolean}){const list=brands.map((name,i)=>({name,src:Object.entries(logoModules).find(([p])=>p.includes(`/${logoNames[i]}.`))?.[1]}));const items=marquee?[...list,...list]:list;return <div className={cn(marquee?'logo-marquee overflow-hidden':'grid grid-cols-2 md:grid-cols-3')}><div className={cn(marquee?'logo-track flex w-max':'contents')}>{items.map((b,i)=><div key={`${b.name}-${i}`} className={cn('flex h-24 min-w-48 items-center justify-center border border-border bg-background px-7 grayscale transition duration-300 hover:border-primary hover:grayscale-0',!marquee&&'min-w-0')}>{b.src?<img src={b.src} alt={b.name} className="max-h-9 max-w-36"/>:<span className="text-center text-sm font-extrabold uppercase text-muted-foreground">{b.name}</span>}</div>)}</div></div>}
export function CountUp({value}:{value:string}){const ref=useRef<HTMLSpanElement>(null);const[shown,setShown]=useState('0');useEffect(()=>{const el=ref.current;if(!el)return;const target=parseInt(value,10);const suffix=value.replace(String(target),'');const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;const o=new IntersectionObserver(([e])=>{if(!e?.isIntersecting)return;o.disconnect();if(reduce){setShown(value);return}let n=0;const id=setInterval(()=>{n++;setShown(`${n}${suffix}`);if(n>=target)clearInterval(id)},90);},{threshold:.5});o.observe(el);return()=>o.disconnect()},[value]);return <span ref={ref}>{shown}</span>}
export function GlobalCta(){const{language}=useLanguage();const c=common.cta;return <section className="relative grid overflow-hidden bg-brand lg:grid-cols-2"><div className="blueprint-dark relative px-[max(.75rem,calc((100vw-78rem)/2))] py-14 sm:px-[max(1rem,calc((100vw-78rem)/2))] sm:py-16 lg:py-20 lg:pr-14"><Eyebrow light>{common.contact[language]}</Eyebrow><HighlightTitle text={c.title[language]} className="mt-5 text-3xl text-brand-foreground sm:text-4xl"/><p className="mt-5 max-w-xl text-brand-foreground/75">{c.text[language]}</p><div className="mt-8 grid gap-3 sm:flex sm:flex-wrap"><ButtonLink to="/contact" className="w-full sm:w-auto">{common.contact[language]}</ButtonLink><a href="tel:+212662716472" className="inline-flex min-h-12 min-w-0 items-center justify-center gap-2 rounded-sm border border-brand-foreground/35 px-4 text-center text-sm font-bold text-brand-foreground hover:border-primary sm:px-5"><Phone className="h-4 w-4 shrink-0"/><span className="min-w-0">{common.call[language]}</span></a></div></div><div className="relative min-h-64 overflow-hidden sm:min-h-72"><img src={media.cta} alt={c.alt[language]} className="h-full w-full object-cover transition duration-1000 hover:scale-105" width="1920" height="1440" loading="lazy"/><BrandArc className="absolute -left-20 bottom-0 w-64"/></div></section>}
export function Tags({items}:{items:readonly string[]}){return <div className="flex flex-wrap gap-2">{items.map(x=><span key={x} className="rounded-full border border-brand/15 bg-background px-3 py-1.5 text-xs font-bold text-brand"><Check className="mr-1 inline h-3 w-3 text-primary"/>{x}</span>)}</div>}
export function MapGraphic(){return <svg viewBox="0 0 520 300" aria-hidden="true" className="h-full w-full"><defs><pattern id="dots" width="18" height="18" patternUnits="userSpaceOnUse"><circle cx="3" cy="3" r="2" fill="currentColor" opacity=".3"/></pattern></defs><path d="M45 72C136 25 217 65 271 92C325 119 396 93 468 138C429 176 397 208 347 241C281 272 229 235 186 206C143 177 85 175 45 72Z" fill="url(#dots)"/><path d="M152 160Q267 83 385 120M152 160Q306 204 420 185" stroke="currentColor" opacity=".35" strokeDasharray="8 8"/><circle cx="152" cy="160" r="9" className="fill-primary map-pulse"/><circle cx="152" cy="160" r="3" className="fill-primary-foreground"/></svg>}
